name: isabelschoeps-github

on: [push, pull_request]

jobs:
  fontship:
    runs-on: ubuntu-20.04
    name: Fontship
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: |
          git fetch --prune --tags ||:
      - name: Fontship make
        id: fontship
        uses: theleagueof/fontship@v0.8.2
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.fontship.outputs.DISTDIR }}
          path: ${{ steps.fontship.outputs.DISTDIR }}.zip
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.fontship.outputs.DISTDIR }}.zip
            ${{ steps.fontship.outputs.DISTDIR }}.tar.xz
